// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CRDTFormats.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Eventuate.Serialization.Proto {

  /// <summary>Holder for reflection information generated from CRDTFormats.proto</summary>
  internal static partial class CRDTFormatsReflection {

    #region Descriptor
    /// <summary>File descriptor for CRDTFormats.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CRDTFormatsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDUkRURm9ybWF0cy5wcm90bxIdRXZlbnR1YXRlLlNlcmlhbGl6YXRpb24u",
            "UHJvdG8aE0NvbW1vbkZvcm1hdHMucHJvdG8iaQoLT1JTZXRGb3JtYXQSSAoQ",
            "dmVyc2lvbmVkRW50cmllcxgBIAMoCzIuLkV2ZW50dWF0ZS5TZXJpYWxpemF0",
            "aW9uLlByb3RvLlZlcnNpb25lZEZvcm1hdBIQCghjbGFzc1RhZxgCIAEoBSJJ",
            "CgxPUkNhcnRGb3JtYXQSOQoFb3JTZXQYASABKAsyKi5FdmVudHVhdGUuU2Vy",
            "aWFsaXphdGlvbi5Qcm90by5PUlNldEZvcm1hdCJgChFPUkNhcnRFbnRyeUZv",
            "cm1hdBI5CgNrZXkYASABKAsyLC5FdmVudHVhdGUuU2VyaWFsaXphdGlvbi5Q",
            "cm90by5QYXlsb2FkRm9ybWF0EhAKCHF1YW50aXR5GAIgASgFIlgKEUxXV1Jl",
            "Z2lzdGVyRm9ybWF0EkMKCm12UmVnaXN0ZXIYASABKAsyLy5FdmVudHVhdGUu",
            "U2VyaWFsaXphdGlvbi5Qcm90by5NVlJlZ2lzdGVyRm9ybWF0ImcKEE1WUmVn",
            "aXN0ZXJGb3JtYXQSQQoJdmVyc2lvbmVkGAEgAygLMi4uRXZlbnR1YXRlLlNl",
            "cmlhbGl6YXRpb24uUHJvdG8uVmVyc2lvbmVkRm9ybWF0EhAKCGNsYXNzVGFn",
            "GAIgASgFIlUKElZhbHVlVXBkYXRlZEZvcm1hdBI/CglvcGVyYXRpb24YASAB",
            "KAsyLC5FdmVudHVhdGUuU2VyaWFsaXphdGlvbi5Qcm90by5QYXlsb2FkRm9y",
            "bWF0Ik0KDlVwZGF0ZU9wRm9ybWF0EjsKBWRlbHRhGAEgASgLMiwuRXZlbnR1",
            "YXRlLlNlcmlhbGl6YXRpb24uUHJvdG8uUGF5bG9hZEZvcm1hdCJNCg5Bc3Np",
            "Z25PcEZvcm1hdBI7CgV2YWx1ZRgBIAEoCzIsLkV2ZW50dWF0ZS5TZXJpYWxp",
            "emF0aW9uLlByb3RvLlBheWxvYWRGb3JtYXQiSgoLQWRkT3BGb3JtYXQSOwoF",
            "ZW50cnkYASABKAsyLC5FdmVudHVhdGUuU2VyaWFsaXphdGlvbi5Qcm90by5Q",
            "YXlsb2FkRm9ybWF0IpIBCg5SZW1vdmVPcEZvcm1hdBI7CgVlbnRyeRgBIAEo",
            "CzIsLkV2ZW50dWF0ZS5TZXJpYWxpemF0aW9uLlByb3RvLlBheWxvYWRGb3Jt",
            "YXQSQwoKdGltZXN0YW1wcxgCIAMoCzIvLkV2ZW50dWF0ZS5TZXJpYWxpemF0",
            "aW9uLlByb3RvLlZlY3RvclRpbWVGb3JtYXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Eventuate.Serialization.Proto.CommonFormatsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.ORSetFormat), global::Eventuate.Serialization.Proto.ORSetFormat.Parser, new[]{ "VersionedEntries", "ClassTag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.ORCartFormat), global::Eventuate.Serialization.Proto.ORCartFormat.Parser, new[]{ "OrSet" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.ORCartEntryFormat), global::Eventuate.Serialization.Proto.ORCartEntryFormat.Parser, new[]{ "Key", "Quantity" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.LWWRegisterFormat), global::Eventuate.Serialization.Proto.LWWRegisterFormat.Parser, new[]{ "MvRegister" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.MVRegisterFormat), global::Eventuate.Serialization.Proto.MVRegisterFormat.Parser, new[]{ "Versioned", "ClassTag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.ValueUpdatedFormat), global::Eventuate.Serialization.Proto.ValueUpdatedFormat.Parser, new[]{ "Operation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.UpdateOpFormat), global::Eventuate.Serialization.Proto.UpdateOpFormat.Parser, new[]{ "Delta" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.AssignOpFormat), global::Eventuate.Serialization.Proto.AssignOpFormat.Parser, new[]{ "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.AddOpFormat), global::Eventuate.Serialization.Proto.AddOpFormat.Parser, new[]{ "Entry" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eventuate.Serialization.Proto.RemoveOpFormat), global::Eventuate.Serialization.Proto.RemoveOpFormat.Parser, new[]{ "Entry", "Timestamps" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class ORSetFormat : pb::IMessage<ORSetFormat> {
    private static readonly pb::MessageParser<ORSetFormat> _parser = new pb::MessageParser<ORSetFormat>(() => new ORSetFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ORSetFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORSetFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORSetFormat(ORSetFormat other) : this() {
      versionedEntries_ = other.versionedEntries_.Clone();
      classTag_ = other.classTag_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORSetFormat Clone() {
      return new ORSetFormat(this);
    }

    /// <summary>Field number for the "versionedEntries" field.</summary>
    public const int VersionedEntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Eventuate.Serialization.Proto.VersionedFormat> _repeated_versionedEntries_codec
        = pb::FieldCodec.ForMessage(10, global::Eventuate.Serialization.Proto.VersionedFormat.Parser);
    private readonly pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat> versionedEntries_ = new pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat> VersionedEntries {
      get { return versionedEntries_; }
    }

    /// <summary>Field number for the "classTag" field.</summary>
    public const int ClassTagFieldNumber = 2;
    private int classTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClassTag {
      get { return classTag_; }
      set {
        classTag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ORSetFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ORSetFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!versionedEntries_.Equals(other.versionedEntries_)) return false;
      if (ClassTag != other.ClassTag) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= versionedEntries_.GetHashCode();
      if (ClassTag != 0) hash ^= ClassTag.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      versionedEntries_.WriteTo(output, _repeated_versionedEntries_codec);
      if (ClassTag != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClassTag);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += versionedEntries_.CalculateSize(_repeated_versionedEntries_codec);
      if (ClassTag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClassTag);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ORSetFormat other) {
      if (other == null) {
        return;
      }
      versionedEntries_.Add(other.versionedEntries_);
      if (other.ClassTag != 0) {
        ClassTag = other.ClassTag;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            versionedEntries_.AddEntriesFrom(input, _repeated_versionedEntries_codec);
            break;
          }
          case 16: {
            ClassTag = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  internal sealed partial class ORCartFormat : pb::IMessage<ORCartFormat> {
    private static readonly pb::MessageParser<ORCartFormat> _parser = new pb::MessageParser<ORCartFormat>(() => new ORCartFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ORCartFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartFormat(ORCartFormat other) : this() {
      OrSet = other.orSet_ != null ? other.OrSet.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartFormat Clone() {
      return new ORCartFormat(this);
    }

    /// <summary>Field number for the "orSet" field.</summary>
    public const int OrSetFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.ORSetFormat orSet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.ORSetFormat OrSet {
      get { return orSet_; }
      set {
        orSet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ORCartFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ORCartFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrSet, other.OrSet)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (orSet_ != null) hash ^= OrSet.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (orSet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OrSet);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (orSet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrSet);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ORCartFormat other) {
      if (other == null) {
        return;
      }
      if (other.orSet_ != null) {
        if (orSet_ == null) {
          orSet_ = new global::Eventuate.Serialization.Proto.ORSetFormat();
        }
        OrSet.MergeFrom(other.OrSet);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (orSet_ == null) {
              orSet_ = new global::Eventuate.Serialization.Proto.ORSetFormat();
            }
            input.ReadMessage(orSet_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class ORCartEntryFormat : pb::IMessage<ORCartEntryFormat> {
    private static readonly pb::MessageParser<ORCartEntryFormat> _parser = new pb::MessageParser<ORCartEntryFormat>(() => new ORCartEntryFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ORCartEntryFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartEntryFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartEntryFormat(ORCartEntryFormat other) : this() {
      Key = other.key_ != null ? other.Key.Clone() : null;
      quantity_ = other.quantity_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ORCartEntryFormat Clone() {
      return new ORCartEntryFormat(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ORCartEntryFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ORCartEntryFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Key, other.Key)) return false;
      if (Quantity != other.Quantity) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (key_ != null) hash ^= Key.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (key_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Key);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quantity);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (key_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Key);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ORCartEntryFormat other) {
      if (other == null) {
        return;
      }
      if (other.key_ != null) {
        if (key_ == null) {
          key_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Key.MergeFrom(other.Key);
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (key_ == null) {
              key_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(key_);
            break;
          }
          case 16: {
            Quantity = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  internal sealed partial class LWWRegisterFormat : pb::IMessage<LWWRegisterFormat> {
    private static readonly pb::MessageParser<LWWRegisterFormat> _parser = new pb::MessageParser<LWWRegisterFormat>(() => new LWWRegisterFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LWWRegisterFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LWWRegisterFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LWWRegisterFormat(LWWRegisterFormat other) : this() {
      MvRegister = other.mvRegister_ != null ? other.MvRegister.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LWWRegisterFormat Clone() {
      return new LWWRegisterFormat(this);
    }

    /// <summary>Field number for the "mvRegister" field.</summary>
    public const int MvRegisterFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.MVRegisterFormat mvRegister_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.MVRegisterFormat MvRegister {
      get { return mvRegister_; }
      set {
        mvRegister_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LWWRegisterFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LWWRegisterFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MvRegister, other.MvRegister)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mvRegister_ != null) hash ^= MvRegister.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mvRegister_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MvRegister);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mvRegister_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MvRegister);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LWWRegisterFormat other) {
      if (other == null) {
        return;
      }
      if (other.mvRegister_ != null) {
        if (mvRegister_ == null) {
          mvRegister_ = new global::Eventuate.Serialization.Proto.MVRegisterFormat();
        }
        MvRegister.MergeFrom(other.MvRegister);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (mvRegister_ == null) {
              mvRegister_ = new global::Eventuate.Serialization.Proto.MVRegisterFormat();
            }
            input.ReadMessage(mvRegister_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class MVRegisterFormat : pb::IMessage<MVRegisterFormat> {
    private static readonly pb::MessageParser<MVRegisterFormat> _parser = new pb::MessageParser<MVRegisterFormat>(() => new MVRegisterFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MVRegisterFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MVRegisterFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MVRegisterFormat(MVRegisterFormat other) : this() {
      versioned_ = other.versioned_.Clone();
      classTag_ = other.classTag_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MVRegisterFormat Clone() {
      return new MVRegisterFormat(this);
    }

    /// <summary>Field number for the "versioned" field.</summary>
    public const int VersionedFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Eventuate.Serialization.Proto.VersionedFormat> _repeated_versioned_codec
        = pb::FieldCodec.ForMessage(10, global::Eventuate.Serialization.Proto.VersionedFormat.Parser);
    private readonly pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat> versioned_ = new pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Eventuate.Serialization.Proto.VersionedFormat> Versioned {
      get { return versioned_; }
    }

    /// <summary>Field number for the "classTag" field.</summary>
    public const int ClassTagFieldNumber = 2;
    private int classTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClassTag {
      get { return classTag_; }
      set {
        classTag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MVRegisterFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MVRegisterFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!versioned_.Equals(other.versioned_)) return false;
      if (ClassTag != other.ClassTag) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= versioned_.GetHashCode();
      if (ClassTag != 0) hash ^= ClassTag.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      versioned_.WriteTo(output, _repeated_versioned_codec);
      if (ClassTag != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClassTag);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += versioned_.CalculateSize(_repeated_versioned_codec);
      if (ClassTag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClassTag);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MVRegisterFormat other) {
      if (other == null) {
        return;
      }
      versioned_.Add(other.versioned_);
      if (other.ClassTag != 0) {
        ClassTag = other.ClassTag;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            versioned_.AddEntriesFrom(input, _repeated_versioned_codec);
            break;
          }
          case 16: {
            ClassTag = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  internal sealed partial class ValueUpdatedFormat : pb::IMessage<ValueUpdatedFormat> {
    private static readonly pb::MessageParser<ValueUpdatedFormat> _parser = new pb::MessageParser<ValueUpdatedFormat>(() => new ValueUpdatedFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValueUpdatedFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueUpdatedFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueUpdatedFormat(ValueUpdatedFormat other) : this() {
      Operation = other.operation_ != null ? other.Operation.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueUpdatedFormat Clone() {
      return new ValueUpdatedFormat(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat operation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValueUpdatedFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValueUpdatedFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Operation, other.Operation)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (operation_ != null) hash ^= Operation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (operation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Operation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (operation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Operation);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValueUpdatedFormat other) {
      if (other == null) {
        return;
      }
      if (other.operation_ != null) {
        if (operation_ == null) {
          operation_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Operation.MergeFrom(other.Operation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (operation_ == null) {
              operation_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(operation_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class UpdateOpFormat : pb::IMessage<UpdateOpFormat> {
    private static readonly pb::MessageParser<UpdateOpFormat> _parser = new pb::MessageParser<UpdateOpFormat>(() => new UpdateOpFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateOpFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateOpFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateOpFormat(UpdateOpFormat other) : this() {
      Delta = other.delta_ != null ? other.Delta.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateOpFormat Clone() {
      return new UpdateOpFormat(this);
    }

    /// <summary>Field number for the "delta" field.</summary>
    public const int DeltaFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat delta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Delta {
      get { return delta_; }
      set {
        delta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateOpFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateOpFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Delta, other.Delta)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (delta_ != null) hash ^= Delta.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (delta_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Delta);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (delta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Delta);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateOpFormat other) {
      if (other == null) {
        return;
      }
      if (other.delta_ != null) {
        if (delta_ == null) {
          delta_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Delta.MergeFrom(other.Delta);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (delta_ == null) {
              delta_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(delta_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class AssignOpFormat : pb::IMessage<AssignOpFormat> {
    private static readonly pb::MessageParser<AssignOpFormat> _parser = new pb::MessageParser<AssignOpFormat>(() => new AssignOpFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AssignOpFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignOpFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignOpFormat(AssignOpFormat other) : this() {
      Value = other.value_ != null ? other.Value.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignOpFormat Clone() {
      return new AssignOpFormat(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AssignOpFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AssignOpFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Value, other.Value)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (value_ != null) hash ^= Value.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (value_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Value);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (value_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AssignOpFormat other) {
      if (other == null) {
        return;
      }
      if (other.value_ != null) {
        if (value_ == null) {
          value_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Value.MergeFrom(other.Value);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (value_ == null) {
              value_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(value_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class AddOpFormat : pb::IMessage<AddOpFormat> {
    private static readonly pb::MessageParser<AddOpFormat> _parser = new pb::MessageParser<AddOpFormat>(() => new AddOpFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddOpFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddOpFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddOpFormat(AddOpFormat other) : this() {
      Entry = other.entry_ != null ? other.Entry.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddOpFormat Clone() {
      return new AddOpFormat(this);
    }

    /// <summary>Field number for the "entry" field.</summary>
    public const int EntryFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat entry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Entry {
      get { return entry_; }
      set {
        entry_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddOpFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddOpFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Entry, other.Entry)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (entry_ != null) hash ^= Entry.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (entry_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Entry);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (entry_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entry);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddOpFormat other) {
      if (other == null) {
        return;
      }
      if (other.entry_ != null) {
        if (entry_ == null) {
          entry_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Entry.MergeFrom(other.Entry);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (entry_ == null) {
              entry_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(entry_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class RemoveOpFormat : pb::IMessage<RemoveOpFormat> {
    private static readonly pb::MessageParser<RemoveOpFormat> _parser = new pb::MessageParser<RemoveOpFormat>(() => new RemoveOpFormat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoveOpFormat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eventuate.Serialization.Proto.CRDTFormatsReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveOpFormat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveOpFormat(RemoveOpFormat other) : this() {
      Entry = other.entry_ != null ? other.Entry.Clone() : null;
      timestamps_ = other.timestamps_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveOpFormat Clone() {
      return new RemoveOpFormat(this);
    }

    /// <summary>Field number for the "entry" field.</summary>
    public const int EntryFieldNumber = 1;
    private global::Eventuate.Serialization.Proto.PayloadFormat entry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Eventuate.Serialization.Proto.PayloadFormat Entry {
      get { return entry_; }
      set {
        entry_ = value;
      }
    }

    /// <summary>Field number for the "timestamps" field.</summary>
    public const int TimestampsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Eventuate.Serialization.Proto.VectorTimeFormat> _repeated_timestamps_codec
        = pb::FieldCodec.ForMessage(18, global::Eventuate.Serialization.Proto.VectorTimeFormat.Parser);
    private readonly pbc::RepeatedField<global::Eventuate.Serialization.Proto.VectorTimeFormat> timestamps_ = new pbc::RepeatedField<global::Eventuate.Serialization.Proto.VectorTimeFormat>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Eventuate.Serialization.Proto.VectorTimeFormat> Timestamps {
      get { return timestamps_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoveOpFormat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoveOpFormat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Entry, other.Entry)) return false;
      if(!timestamps_.Equals(other.timestamps_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (entry_ != null) hash ^= Entry.GetHashCode();
      hash ^= timestamps_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (entry_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Entry);
      }
      timestamps_.WriteTo(output, _repeated_timestamps_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (entry_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entry);
      }
      size += timestamps_.CalculateSize(_repeated_timestamps_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoveOpFormat other) {
      if (other == null) {
        return;
      }
      if (other.entry_ != null) {
        if (entry_ == null) {
          entry_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
        }
        Entry.MergeFrom(other.Entry);
      }
      timestamps_.Add(other.timestamps_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (entry_ == null) {
              entry_ = new global::Eventuate.Serialization.Proto.PayloadFormat();
            }
            input.ReadMessage(entry_);
            break;
          }
          case 18: {
            timestamps_.AddEntriesFrom(input, _repeated_timestamps_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
